Support compat addresses for ibc-in
penumbra-zone/web pull request #1079
Opened 2024-05-09 15:04 UTC by grod220

Closes https://github.com/penumbra-zone/web/issues/1053

For noble, we need to encode our addresses to bech32 (not bech32m). In core, we have a special prefix for this specific case: https://github.com/penumbra-zone/penumbra/blob/main/crates/proto/src/serializers/bech32str.rs#L146.

Amended our bech32m package to support this new encoding method.

2024-05-09 15:45 UTC, Valentine1898 commented
How long will the ibc transfer from noble take? 
I sent a transaction, but my balance in noble has changed only by the value of the fee  🤔

2024-05-09 15:50 UTC, grod220 commented
Currently the client state has expired. We'll need to work with the protocol team in getting these back up before we get a successful transfer. However, after this PR, we are no longer getting the bech32 error like we had before. Thanks for testing though!

2024-05-09 17:22 UTC, turbocrime commented on apps/minifront/src/state/ibc-in.ts
> + */
i would add this information to the readme as well

2024-05-09 17:31 UTC, turbocrime requested changes

2024-05-09 17:31 UTC, turbocrime commented on packages/bech32m/src/penumbracompat1.ts
rename to just `penumbracompat.ts` to match other files in this dir

2024-05-09 17:38 UTC, turbocrime commented
suggestions in https://github.com/penumbra-zone/web/pull/1083

2024-05-09 19:43 UTC, grod220 commented on packages/bech32m/src/penumbracompat1.ts
But aren't these files named according to the prefix? For some reason, this prefix uniquely has the 1 in it: https://github.com/penumbra-zone/penumbra/blob/d13d731fadd665d7f2ec38c3bde57f53b2e86891/crates/proto/src/serializers/bech32str.rs#L146

2024-05-10 09:49 UTC, grod220 commented on packages/bech32m/src/penumbracompat1.ts
I also wonder if it has this number in it because we may need to have `penumbracompat2` for some other chain in the future.

2024-05-10 16:52 UTC, turbocrime commented on packages/bech32m/src/penumbracompat1.ts
interesting. 1 is a valid prefix character, but it is also the separator character, and this may be a bug in core or has some unexplained meaning like version as you suggest.

i can't find any examples or documentation on this.

cc @avahowell you committed the `penumbracompat1` in core?

2024-05-10 17:04 UTC, turbocrime approved these changes

2024-05-10 17:26 UTC, merged