Fix: #1226: Swap wallet balances
penumbra-zone/web pull request #1252
Opened 2024-06-04 20:29 UTC by VanishMax

Closes #1226 

The result:

<img width="826" alt="image" src="https://github.com/penumbra-zone/web/assets/29180358/c2d8ee00-e718-4671-a91f-f3578f9a82f6">

A trade screen now has an out-balance under the selected token. So, if users choose "Account 1 UM" as in-token and "Account 1 USDC", then the account 1's balance will be displayed. If account numbers mismatch, the "0" will be printed.

Please, take a look at the `balanceOut` memo calculation. It has a monstrous computed function and I hope you can tell how to make it neat 🙏

2024-06-05 17:04 UTC, jessepinho requested changes
Nice work! Overall looks good, but there are a couple changes I'd make to how you're getting the asset out balance. I'll mark this as "Request changes" so I can re-review, but feel free to reach out on Discord to pair on this.

2024-06-06 08:58 UTC, VanishMax commented
Thanks, @jessepinho! Is was nice finding out about the getters. I shortened the memo function, created a couple more getters and it looks surely cleaner now

2024-06-07 15:07 UTC, grod220 approved these changes
_(Paired on additional commit from me)_

Good job!

2024-06-11 16:32 UTC, jessepinho approved these changes
LGTM! Added a couple comments, including one about the merge conflict. Merge when those are addressed!

2024-06-11 16:58 UTC, VanishMax commented on apps/minifront/src/components/swap/swap-form/token-swap-input.tsx
> +      assetOut &&
Thanks, good addition! Changed this line

2024-06-11 16:58 UTC, VanishMax commented on apps/minifront/src/components/swap/swap-form/token-swap-input.tsx
> -        {priceHistory.startMetadata && priceHistory.endMetadata && priceHistory.candles.length && (
Yeah, I made a fix for this before the merge conficts. Updated it now

2024-06-11 17:38 UTC, merged