Add Slider component
penumbra-zone/web pull request #1738
Opened 2024-08-28 11:50 UTC by JasonMHasperhoven

Implements https://github.com/penumbra-zone/web/issues/1715

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/33f3400d-d0bc-40f5-b952-ba405ed069fe">

2024-08-28 14:57 UTC, VanishMax requested changes

2024-08-28 14:57 UTC, VanishMax commented on packages/ui/src/Slider/index.test.tsx
> +  it('renders correctly', () => {
thought: that's not a meaningful test. UI interactions could be properly tested.

suggestion: for this test, you can render the component, simulate a click to some point of the slider, mock the `onChange` function and expect the correct value to be passed to it.

2024-08-28 14:57 UTC, VanishMax commented on packages/ui/src/Slider/index.tsx
> +const TRACK_GAP_WIDTH = '4px';
todo (blocking): use `${props => props.theme.spacing(4)}` to get the correct value for any spacing property in css. Sam tries to use all theme values everywhere in Figma (see the screenshot), so should we

<img width="697" alt="image" src="https://github.com/user-attachments/assets/a1c21071-fc06-4a05-8f91-98c88161f4f6">

2024-08-28 14:57 UTC, VanishMax commented on packages/ui/src/Slider/index.tsx
> +export const Slider: React.FC<SliderProps> = ({
issue (blocking): this Slider is not a11y-compliant. You can check the [W3C standards for a Slider](https://www.w3.org/WAI/ARIA/apg/patterns/slider/) – it describes the patterns we should implement to provide the keyboard accessibility and help the users with low vision. For example, the standards say that the value can be controlled via pressing left or arrow keys when the Slider is focused.

So far, Jesse, Sam and me tried to comply with a11y standards in the design and code. If you open v2 pages, tabbing around shows correct focus state for any component, and it responds not only to the "enter press" but also to any other keyboard key. I believe we could do the same with Slider 🙏

suggestion: use [Radix's Slider component](https://www.radix-ui.com/primitives/docs/components/slider) as a base to handle the a11y and even simplify the code.

2024-08-29 16:36 UTC, VanishMax approved these changes
Loving the result!

2024-08-30 06:58 UTC, TalDerei reviewed
LGTM

2024-09-03 11:20 UTC, merged